# Site settings
title: Jekyll 3.x.x. Test Site
email: jekyll@tester.com
description: >- # this means to ignore newlines until "baseurl:"
  Plain Jekyll installation to test plugin versions
baseurl: "" 
url: "https://erikw.github.io/jekyll-3.x.x-test/" 
github_username:  erikw

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/



google_search_console:
  verification_file_code: 1234


